version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: fila-livre-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: fila_livre
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  backend:
    image: golang:1.20
    container_name: fila-livre-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/pkg/mod
    command: sh -c "go mod download && go run cmd/api/main.go"
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mysql_data: